# Generated by Django 5.2.17 on 2026-09-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('inscricoes_abertas', models.BooleanField(default=True)),
                ('organizador', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bloco', models.CharField(max_length=50)),
                ('capacidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('responsavel', models.CharField(max_length=150)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='eventos.evento')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='eventos.sala')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante', models.CharField(max_length=150)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.atividade')),
                ('inscricao_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_atividades', to='eventos.inscricaoevento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inscricaoevento',
            constraint=models.UniqueConstraint(fields=('evento', 'participante'), name='inscricao_unica_evento'),
        ),
        migrations.AddConstraint(
            model_name='inscricaoatividade',
            constraint=models.UniqueConstraint(fields=('inscricao_evento', 'atividade'), name='inscricao_unica_atividade'),
        ),
    ]
